name: Hello Universe
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dzemic/cars@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
